### ISSUE TITLE
콘솔 오류

### ISSUE THREAD

**Issue by NbverHub** [wkpark/moniwiki#150]
다음과 같은 오류가 콘솔창에 나타납니다.

```
Uncaught TypeError: $(...).autocomplete is not a function
    at HTMLDocument.<anonymous> (ac.js:55:19)
    at fire (jquery-1.9.1.js:1037:30)
    at Object.fireWith [as resolveWith] (jquery-1.9.1.js:1148:7)
    at Function.ready (jquery-1.9.1.js:433:13)
    at HTMLDocument.completed (jquery-1.9.1.js:103:11)
```
```
FrontPage:116 Uncaught TypeError: $(...).draggable is not a function
    at HTMLDocument.<anonymous> (FrontPage:116:13)
    at j (jquery.js:3148:30)
    at Object.fireWith [as resolveWith] (jquery.js:3260:7)
    at Function.ready (jquery.js:3472:13)
    at HTMLDocument.J (jquery.js:3503:10)
```

**Comment by wkpark** [comment]
아마도 이건 오래된 버그같네요. 맞는지요?

사용중인 브라우저 및, `jquery.js` 로딩 지정방식 (`config.php` 상에서)을 알려주시면 참고가 되겠습니다.

최근에 관련 문제가 수정되었는데 확인해봐야 할 것 같네요.

**Comment by NbverHub** [comment]
브라우저는 웨일입니다.

```
# set global javascripts (lowlevel)
#$js=<<<EOF
#<script type="text/javascript" src="$url_prefix/local/ajax.js"></script>
#<script type="text/javascript" src="$url_prefix/local/se.js"></script>
#<script type="text/javascript" src="$url_prefix/local/Wikiwyg/lib/Wikiwyg.js"></script>
#<script type="text/javascript" src="$url_prefix/local/Wikiwyg/lib/Wikiwyg/Util.js"></script>
#<script type="text/javascript" src="$url_prefix/local/Wikiwyg/lib/Wikiwyg/Toolbar.js"></script>
#<script type="text/javascript" src="$url_prefix/local/Wikiwyg/lib/Wikiwyg/Wikitext.js"></script>
#<script type="text/javascript" src="$url_prefix/local/Wikiwyg/lib/Wikiwyg/Preview.js"></script>
#<script type="text/javascript" src="$url_prefix/local/Wikiwyg/lib/Wikiwyg/HTML.js"></script>
#<script type="text/javascript" src="$url_prefix/local/Wikiwyg/lib/Wikiwyg/Wysiwyg.js"></script>
#<script type="text/javascript" src="$url_prefix/local/moniwyg.js"></script>
#
#<script type="text/javascript" src="$url_prefix/local/js/prototype.js"></script>
#<script type="text/javascript" src="$url_prefix/local/js/scriptaculous.js?load=effects,controls"></script>
#<script type="text/javascript" src="$url_prefix/local/lightbox2/js/lightbox.js"></script>
#<link rel="stylesheet" href="$url_prefix/local/lightbox2/css/lightbox.css" type="text/css" media="screen" />
#<script type="text/javascript" src="$url_prefix/local/autocomplete.js"></script>
#<script type="text/javascript" src="$url_prefix/local/subindex.js"></script>
#EOF;
# alternatively you can use the $javascripts option (more inteligent method)
$javascripts=array(
	'js/i18n.js',
	'<script src="http://code.jquery.com/jquery-1.9.1.js"></script>',
	'<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>',
    'ac.js',
	'footnotes.js',
	'pasta.js',
	'ajax.js',
	'ASCIIMathML.js',
	);
```

**Comment by wkpark** [comment]
~~~.php
<?php
$javascripts=array(
	'js/i18n.js',
	'<script src="http://code.jquery.com/jquery-1.9.1.js"></script>',
	'<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>',
    'ac.js',
	'footnotes.js',
	'pasta.js',
	'ajax.js',
	'ASCIIMathML.js',
	);
~~~
순서상 `'ajax.js'`가 `jquery.js` 이전 혹은 그 다음에 위치해야 합니다. `ac.js` (autocomplete)는 `ajax.js` 다음으로 위치해야 호고요. `ac.js`가 `ajax.js`에 정의되어 있는 `HTTPGet()`을 사용하기때문입니다.

**Comment by NbverHub** [comment]
```
$javascripts=array(
	'js/i18n.js',
	'<script src="http://code.jquery.com/jquery-1.9.1.js"></script>',
	'<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>',
	'ajax.js',
        'ac.js',
	'footnotes.js',
	'pasta.js',
	'ASCIIMathML.js',
	);
```

다음과 같이 수정했더니 다음 오류가 추가로 나타납니다.

```
Uncaught TypeError: $(...).autocomplete is not a function
    at attachAutocomplete (ac.js:55:19)
```

**Comment by wkpark** [comment]
`ac.js`에서 `attachAutocomplete`는 최근에 추가된 것이니 모니위키 비교적 최신 버전을 사용하고 계신 것으로 생각됩니다.

 위 오류는 jquery가 로딩되었으나 jquery-ui는 로딩이 완료되지 않은 채 ac.js에서 autocomplete를 시도하고 있기 때문에 발생하는 문제입니다.

![image](https://user-images.githubusercontent.com/232347/201158595-a4788b33-ba97-4a46-aae2-b752c6309618.png)

궁금해서 웨일을 직접 설치해보고, minify 안된 jquery 및 jquery-ui.js도 설정해보았습니다. (아래 참고)
(캐시 끄고 해봄)
~~~
        'http://code.jquery.com/jquery-1.9.1.js',
        'http://code.jquery.com/ui/1.10.3/jquery-ui.js',
        #'defer,//code.jquery.com/jquery-3.6.1.min.js',
        #'defer,//code.jquery.com/ui/1.13.2/jquery-ui.min.js',
        'ajax.js',
	'ac.js',
~~~

 * minify 안된 jquery.js(80k)라서 로딩이 더 느릴 것이고, jquery-ui.js는 그 크기가 100k나 됩니다. 네트워크 사정이 좋지 않다면 문제될 것으로 보입니다.
 * ac.js는 크기가 2k도 안됩니다.
 * 저는 minify 안된 상태에서 캐시도 끈 채 위의 설정으로 로딩시켰는데도 오류가 안나는군요. (캐시 끄면 로딩이 더 느려짐)
 * minify 된 `jquery-1.9.1.min.js`(~33kB), `jquery-ui.min.js` (60.8kB)로 바꾸면 어떻게 되시나요?
 * 마지막으로, 최신 모니위키를 사용하신다면 `defer` 를 켤 수 있습니다. config.php에서 `'ac.js'` 라고 넣지 말고 `'defer,ac.js'`라고 넣으면 됩니다. 이렇게 하면 `ac.js`가 페이지가 모두 로딩된 후에 가장 늦게 실행됩니다.

아래 스샷은 캐시를 켜고 다시 해본 것 (minify 된 것 사용)
![image](https://user-images.githubusercontent.com/232347/201162695-ab855e28-e182-4c5e-afeb-8217e8ec2372.png)
